#! /usr/bin/env ruby

require "pg"
require "io/console"

class ExpenseData
  def initialize
    @connection = PG.connect(dbname: "expenses")
    setup_schema
  end

  def list_all_expenses
    sql = "SELECT * FROM expenses;"
    all_rows = @connection.exec(sql)
    display_count(all_rows)
    display_items(all_rows) if all_rows.ntuples > 1
  end

  def add_new_expense(amount, memo)
    sql = <<~SQL
    INSERT INTO expenses (amount, memo)
    VALUES ($1, $2);
    SQL
    @connection.exec_params(sql, [amount, memo])

    puts 'Expenses have been updated.'
  end

  def search_expenses(term)
    sql = <<~SQL
    SELECT * FROM expenses
    WHERE memo ILIKE $1;
    SQL

    matching_terms = @connection.exec_params(sql, ["%#{term}%"])

    display_count(matching_terms)
    display_items(matching_terms) if matching_terms.ntuples > 0
  end

  def delete_expense(id)
    select_sql = "SELECT * FROM expenses WHERE id = $1"
    removed_item = @connection.exec_params(select_sql, [id])
    
    if removed_item.ntuple == 1
      delete_sql = "DELETE FROM expenses WHERE id = $1;"
      @connection.exec_params(delete_sql, [id])
      puts "The following item has been removed:"
      display_items(removed_item)
    else
      puts "There is no item with id #{id}."
    end
  end

  def delete_all_expenses
    sql = "DELETE FROM expenses"
    @connection.exec(sql)
    
    puts 'All expenses have been deleted.'
  end

  private

  def setup_schema
    result = @connection.exec <<~SQL
    SELECT COUNT(*)
    FROM information_schema.tables
    WHERE table_schema = 'public' 
    AND table_name = 'expenses';
    SQL

    if result[0]['count'] == 0
      @connection.exec <<~SQL
      CREATE TABLE expenses (
        id serial PRIMARY KEY,
        amount numeric(6,2) NOT NULL,
        memo text NOT NULL,
        created_on date NOT NULL DEFAULT current_date 
      );
      SQL
    end

  end

  def display_count(result)
    case result.ntuples
    when 0
      puts 'There are no expenses.'
    when 1 
      puts "There is 1 expense."
    else
      puts "There are #{result.ntuples} expenses."
    end
  end

  def display_items(result)
    result.each do |tuple|
      puts "#{tuple['id'].rjust(2)} | #{tuple['created_on']} | #{tuple['amount'].rjust(7)} | #{tuple['memo']}"
    end

    amount_sum = result.field_values('amount').map(&:to_f).sum

    puts '-' * 50
    puts "Total: #{format('%.2f', amount_sum).rjust(18)}"
  end
end

class CLI
  def initialize
    @application = ExpenseData.new
  end

  def run(arguments)
    command = arguments.shift

    case command
    when 'list'
      @application.list_all_expenses
    when 'add'
      amount = arguments[0]
      memo = arguments[1]

      abort 'You must provide an amount and memo.' unless amount && memo
      @application.add_new_expense(amount, memo)
    when 'search'
      @application.search_expenses(arguments[0])
    when 'delete'
      @application.delete_expense(arguments[0])
    when 'clear'
      puts 'This will remove all expenses. Are you sure? (y/n)'
      answer = $stdin.getch

      @application.delete_all_expenses if answer == 'y'
    else
      display_help
    end
  end

  def display_help
    puts <<~HINT
    An expense recording system

    Commands:

    add AMOUNT MEMO - record a new expense
    clear           - delete all expenses
    list            - list all expenses
    delete NUMBER   - remove expense with id NUMBER
    search QUERY    - list expenses with a matching memo field  
    HINT
  end
end

CLI.new.run(ARGV)

