#! /usr/bin/env ruby

require "pg"

CONNECTION = PG.connect(dbname: "expenses_app")

def list_all_expenses

  all_rows = CONNECTION.exec "SELECT * FROM expenses ORDER BY created_on ASC;"

  all_rows.each do |tuple|
    puts "#{tuple['id'].rjust(2)} | #{tuple['created_on']} | #{tuple['amount'].rjust(7)} | #{tuple['memo']}"
  end
end

def display_help
  puts <<~HINT
  An expense recording system

  Commands:

  add AMOUNT MEMO - record a new expense
  clear           - delete all expenses
  list            - list all expenses
  delete NUMBER   - remove expense with id NUMBER
  search QUERY    - list expenses with a matching memo field  
  HINT
end

def add_new_expense(amount, memo)
  CONNECTION.exec "INSERT INTO expenses (amount, memo) VALUES (#{amount}, '#{memo}');"
  puts 'Expenses have been updated.'
end

command = ARGV.first

case command
when 'list'
  list_all_expenses
when 'add'
  amount = ARGV[1]
  memo = ARGV[2]
  abort 'You must provide an amount and memo.' unless amount && memo
  add_new_expense(amount, memo)
else
  display_help
end
