#! /usr/bin/env ruby

require "pg"

class ExpenseData
  def initialize
    @connection = PG.connect(dbname: "expenses_app")
  end

  def add_new_expense(amount, memo)
    sql = %q(
    INSERT INTO expenses (amount, memo)
    VALUES ($1, $2);
    )
    @connection.exec_params(sql, [amount, memo])

    puts 'Expenses have been updated.'
  end

  def search_expenses(term)
    sql = %q(
    SELECT * FROM expenses
    WHERE memo ILIKE $1;
    )

    matching_terms = @connection.exec_params(sql, ["%#{term}%"])

    display_items(matching_terms)
  end

  private

  def display_items(result)
    result.each do |tuple|
      puts "#{tuple['id'].rjust(2)} | #{tuple['created_on']} | #{tuple['amount'].rjust(7)} | #{tuple['memo']}"
    end
  end
end

class CLI
  def initialize
    @application = ExpenseData.new
  end

  def run(arguments)
    command = arguments.shift

    case command
    when 'list'
      @application.list_all_expenses
    when 'add'
      amount = arguments[0]
      memo = arguments[1]
      abort 'You must provide an amount and memo.' unless amount && memo
      @application.add_new_expense(amount, memo)
    when 'search'
      @application.search_expenses(arguments[0])
    else
      display_help
    end
  end

  def display_help
    puts <<~HINT
    An expense recording system

    Commands:

    add AMOUNT MEMO - record a new expense
    clear           - delete all expenses
    list            - list all expenses
    delete NUMBER   - remove expense with id NUMBER
    search QUERY    - list expenses with a matching memo field  
    HINT
  end
end

CLI.new.run(ARGV)

