source 'https://rubygems.org'

ruby '3.2.2'

gem 'sinatra'         # provides a web framework for http requests/responses
gem 'sinatra-contrib' # has `sinatra/reloader` which automatically reloads code after changes
gem 'erubi'           # templating engine for embedded ruby (erb)
gem 'minitest'        # library of a complete suite of testing facilities
gem 'rack-test'       # library for testing rack applications
gem 'redcarpet'       # library for markdown processing

gem 'rackup', '~> 2.2'
gem 'puma', '~> 6.6'
